
Vagrant.configure(2) do |config|
  config.vm.box = "debian/buster64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.define "vm" do |vm|
    vm.vm.network "forwarded_port", guest: 80, host: 8080, protocol: "tcp"
    vm.vm.hostname = "vm"
    vm.vm.provision "shell", path: "provision.sh"
  end

end
